# Generated by Django 4.2.24 on 2025-09-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wallet_address",
        ),
    ]
