# Generated by Django 4.2.24 on 2025-09-07 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0002_alter_review_unique_together_review_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_sales_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "currency_pi_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "currency_sidra_volume",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Sales Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductViewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="marketplace.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
