# Generated by Django 4.2.24 on 2025-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Escrow",
            fields=[
                (
                    "deal_id",
                    models.CharField(
                        max_length=66, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("FUNDED", "Funded"),
                            ("RELEASED", "Released"),
                            ("REFUNDED", "Refunded"),
                            ("IN_DISPUTE", "In Dispute"),
                        ],
                        default="CREATED",
                        max_length=15,
                    ),
                ),
                (
                    "funding_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "release_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                (
                    "refund_tx_hash",
                    models.CharField(blank=True, max_length=66, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
