# Generated by Django 4.2.24 on 2025-09-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("escrow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escrow",
                to="orders.order",
            ),
        ),
    ]
